# Permalinks
permalink:           pretty

# Setup
title:               nickymarino.com
tagline:             ''
description:         'Description for the sidebar'
url:                 http://nickymarino.com
baseurl:             ''
paginate:            5
paginate-path:       'page:num'
plugins:
  - jekyll-paginate
  - jemoji

# About/contact
author:
  name:              Nicky Marino
  url:               http://nickymarino.com
  twitter:           https://twitter.com/_NickyMarino
  email:             nicky.s.marino@gmail.com
  github:            https://github.com/nickymarino

twitter_feed:        https://twitter.com/NickyMarino_com