# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Nicky Marino
tagline:             ''
description:         'Description for the sidebar'
url:                 http://nickymarino.com
baseurl:             ''
paginate:            5
paginate-path:       'page:num'
plugins:
  - jekyll-paginate
  - jemoji

# About/contact
author:
  name:              Nicky Marino
  url:               https://twitter.com/_NickyMarino
  email:

# Custom vars
version:             1.0.0
